name: Deploy on Push (stanley)

on:
  push:
    branches:
      - stanley  # Bei Pushes auf Branch "stanley" auslösen

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # (Optional) Checkout-Schritt – nur erforderlich, falls du Code in diesem Workflow selbst benötigst
      - name: Check out code
        uses: actions/checkout@v3

      # SSH in den Server und führe dort die Deployment-Befehle aus
      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            time (
              sudo rm -rf /var/dev/quizzgame \
              && sudo mkdir -p /var/dev/quizzgame \
              && sudo chmod 777 /var/dev/quizzgame \
              && git clone -b stanley --single-branch git@github.com:chris738/Quizzgame.git /var/dev/quizzgame \
              && sudo chmod -R 777 /var/dev/quizzgame \
              && sudo docker restart Quizzgame_Webserver_SQL_Dev
            )
