name: Deploy Stanley Branch

on:
  push:
    branches:
      - stanley

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Execute Remote Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: tuxchen.de
        username: deploy
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: /usr/local/bin/deploy-stanley.sh